name = "rolldorado-login-com-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldorado-login.com.pt"
HMAC_KEY = "afb777d5ffc53bdcadc404e7d153c584b32d4a6b2b7d1b87509850dd6e3f0fe0"
COOKIE_NAME = "56y"
PLAY_PATH = "try-now"
BUTTON_ID = "pd8908ec5fbb96798e4bde2d97b53a827"
GATE_SALT = "276cf8d8e76a6dcd"
